DROP TABLE IF EXISTS USER;
CREATE TABLE IF NOT EXISTS USER (
 
    ID int NOT NULL PRIMARY KEY,
    NAME varchar(20),
    EMAIL varchar(50),
    BIRTH timestamp
 
);
INSERT INTO USER VALUES 
(1, 'JUZÉ_TESTE', 'JUZE@GMAIL.COM', '1975-03-29'),
(2, 'CRAUDIO_TESTE', 'CRAUDIO@GMAIL.COM', '1975-03-29'),
(3, 'MANEL_TESTE', 'MANEL@GMAIL.COM', '1975-03-29');